name: Test
on:
  push:
    branches:
      - main
      - beta
      - "[0-9]+.[0-9]+.x"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run tests on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        if: matrix.node-version != 22
        run: npm test

      - name: Run tests with coverage
        if: matrix.node-version == 22
        run: npm run test:coverage

      - name: Collect coverage
        if: matrix.node-version == 22
        uses: coverallsapp/github-action@v2
